server:
  port: 8071
spring:
  application:
    name: service-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.163.129:3306/mall?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: clf
    password: xiaobai1126
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect:
          storage_engine: innodb
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.163.129:8848
rocketmq:
  name-server: 192.168.163.129:9876
