server:
  port: 8081
spring:
  application:
    name: service-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.163.129:3306/mall
    username: clf
    password: xiaobai1126
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect:
          storage_engine: innodb
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.163.129:8848
